version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "10:00"
    timezone: "Europe/Paris"
  open-pull-requests-limit: 10
  reviewers:
  - Meyclem
  ignore:
    - dependency-name: "express"
