name: CI

on:
  push:
    branches:
      - 'CU-ek6534_Firebase-for-preview-apps'

jobs:
  clean-database:
    runs-on: ubuntu-latest
    container:
      image: node:14.15.1

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: install-dependencies
        run: yarn install

      - name: Clean database
        run: yarn fb:clean-preview
        env:
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        